# Generated by Django 6.0.2 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonIntensityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('region_shortname', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField()),
                ('forecast', models.IntegerField()),
                ('actual', models.IntegerField(blank=True, null=True)),
                ('index', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('forecast_generated_at', models.DateTimeField()),
                ('is_national', models.BooleanField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region_id', 'valid_from'], name='carbon_cir_region_from_idx'), models.Index(fields=['is_national', 'valid_from'], name='carbon_cir_nat_from_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__lt', models.F('valid_to'))), name='carbon_cir_valid_from_lt_to_chk'), models.CheckConstraint(condition=models.Q(models.Q(('is_national', True), ('region_id__isnull', True), ('region_shortname__isnull', True)), models.Q(('is_national', False), ('region_id__isnull', False), ('region_shortname__isnull', False)), _connector='OR'), name='carbon_cir_region_nullness_chk')],
            },
        ),
    ]
