# Generated by Django 6.0.2 on 2026-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonintensityrecord',
            name='actual',
            field=models.IntegerField(blank=True, help_text='gCO₂/kWh', null=True),
        ),
        migrations.AlterField(
            model_name='carbonintensityrecord',
            name='forecast',
            field=models.IntegerField(help_text='gCO₂/kWh'),
        ),
    ]
