# Generated by Django 6.0.2 on 2026-02-25 17:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_received', models.IntegerField(default=0)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('fallback_rows', models.IntegerField(default=0)),
                ('total_kwh', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='kWh', max_digits=12)),
                ('total_emissions_kg', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='kgCO₂', max_digits=12)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FleetChargingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=16)),
                ('charged_at', models.DateTimeField(help_text='UTC, timezone-aware datetime')),
                ('region_id', models.CharField(max_length=64)),
                ('region_shortname', models.CharField(db_index=True, max_length=64)),
                ('kwh_consumed', models.DecimalField(decimal_places=3, help_text='kWh', max_digits=10)),
                ('carbon_intensity_used', models.IntegerField(help_text='gCO₂/kWh')),
                ('intensity_type_used', models.CharField(choices=[('regional_forecast', 'Regional forecast'), ('national_actual', 'National actual'), ('national_forecast', 'National forecast')], max_length=64)),
                ('calculated_emissions_kg', models.DecimalField(decimal_places=6, help_text='kgCO₂', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charging_events', to='fleet.fleetuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle_id', 'charged_at'], name='charged_at_from_vehicle_idx'), models.Index(fields=['region_id', 'charged_at'], name='charged_at_from_region_idx'), models.Index(fields=['postcode'], name='postcode_idx')],
            },
        ),
    ]
