# Generated by Django 6.0.2 on 2026-03-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chargerlocation_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chargerlocation',
            name='core_charger_lat_lng_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargerlocation',
            name='core_charger_reg_pcode_idx',
        ),
        migrations.DeleteModel(
            name='ChargerLocation',
        ),
    ]
