# Generated by Django 6.0.2 on 2026-03-12 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('party_id', models.CharField(max_length=10)),
                ('location_id', models.CharField(max_length=255)),
                ('source_provider', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(default='GBR', max_length=3)),
                ('publish', models.BooleanField(default=True)),
                ('charging_when_closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
                ('ingested_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'charger_locations',
                'indexes': [models.Index(fields=['postcode'], name='charger_loc_postcod_19144a_idx'), models.Index(fields=['latitude', 'longitude'], name='charger_loc_latitud_a017ad_idx'), models.Index(fields=['source_provider'], name='charger_loc_source__d99467_idx'), models.Index(fields=['is_active'], name='charger_loc_is_acti_a25630_idx'), models.Index(fields=['ingested_at'], name='charger_loc_ingeste_09ae23_idx')],
                'unique_together': {('party_id', 'location_id')},
            },
        ),
        migrations.CreateModel(
            name='EVSE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('evse_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField()),
                ('ingested_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evses', to='chargers.chargerlocation')),
            ],
            options={
                'db_table': 'evses',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_id', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=10)),
                ('power_type', models.CharField(max_length=20)),
                ('max_voltage', models.IntegerField(blank=True, null=True)),
                ('max_amperage', models.IntegerField(blank=True, null=True)),
                ('max_electric_power', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('ingested_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='chargers.evse')),
            ],
            options={
                'db_table': 'connectors',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_id', models.CharField(max_length=10)),
                ('tariff_id', models.CharField(max_length=255)),
                ('source_provider', models.CharField(max_length=50)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('tariff_alt_text', models.JSONField(blank=True, default=list)),
                ('elements', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tariffs',
                'indexes': [models.Index(fields=['party_id', 'tariff_id'], name='tariffs_party_i_d33621_idx'), models.Index(fields=['is_stale'], name='tariffs_is_stal_bc3ed1_idx'), models.Index(fields=['source_provider'], name='tariffs_source__ab2697_idx'), models.Index(fields=['last_seen_at'], name='tariffs_last_se_9f6c48_idx'), models.Index(fields=['ingested_at'], name='tariffs_ingeste_7b240b_idx')],
                'unique_together': {('party_id', 'tariff_id')},
            },
        ),
        migrations.CreateModel(
            name='ConnectorTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_tariffs', to='chargers.connector')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_tariffs', to='chargers.tariff')),
            ],
            options={
                'db_table': 'connector_tariffs',
            },
        ),
        migrations.AddIndex(
            model_name='evse',
            index=models.Index(fields=['status'], name='evses_status_7f7f51_idx'),
        ),
        migrations.AddIndex(
            model_name='evse',
            index=models.Index(fields=['ingested_at'], name='evses_ingeste_680567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evse',
            unique_together={('location', 'uid')},
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['standard'], name='connectors_standar_bd2293_idx'),
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['ingested_at'], name='connectors_ingeste_bcd72d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together={('evse', 'connector_id')},
        ),
        migrations.AlterUniqueTogether(
            name='connectortariff',
            unique_together={('connector', 'tariff')},
        ),
    ]
