# Generated by Django 6.0.2 on 2026-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chargerlocation',
            name='charger_loc_postcod_19144a_idx',
        ),
        migrations.AddField(
            model_name='chargerlocation',
            name='opening_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargerlocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='evse',
            name='capabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evse',
            name='floor_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evse',
            name='physical_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='charging_when_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='country_code',
            field=models.CharField(blank=True, default='GBR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='ingested_at',
            field=models.DateTimeField(help_text='Timestamp of the ingestion run that last processed this record.'),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag used when an upstream provider stops returning a location.'),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chargerlocation',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='format',
            field=models.CharField(choices=[('SOCKET', 'Socket'), ('CABLE', 'Cable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='connector',
            name='ingested_at',
            field=models.DateTimeField(help_text='Timestamp of the ingestion run that last processed this record.'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='power_type',
            field=models.CharField(choices=[('AC_1_PHASE', 'AC 1 phase'), ('AC_3_PHASE', 'AC 3 phase'), ('DC', 'DC'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='connector',
            name='standard',
            field=models.CharField(choices=[('CHADEMO', 'CHAdeMO'), ('DOMESTIC_A', 'Domestic A'), ('DOMESTIC_B', 'Domestic B'), ('DOMESTIC_C', 'Domestic C'), ('DOMESTIC_D', 'Domestic D'), ('DOMESTIC_E', 'Domestic E'), ('DOMESTIC_F', 'Domestic F'), ('DOMESTIC_G', 'Domestic G'), ('DOMESTIC_H', 'Domestic H'), ('DOMESTIC_I', 'Domestic I'), ('DOMESTIC_J', 'Domestic J'), ('DOMESTIC_K', 'Domestic K'), ('DOMESTIC_L', 'Domestic L'), ('IEC_60309_2_SINGLE_16', 'IEC 60309-2 Single 16A'), ('IEC_60309_2_THREE_16', 'IEC 60309-2 Three 16A'), ('IEC_60309_2_THREE_32', 'IEC 60309-2 Three 32A'), ('IEC_60309_2_THREE_64', 'IEC 60309-2 Three 64A'), ('IEC_62196_T1', 'IEC 62196 Type 1'), ('IEC_62196_T1_COMBO', 'IEC 62196 Type 1 Combo'), ('IEC_62196_T2', 'IEC 62196 Type 2'), ('IEC_62196_T2_COMBO', 'IEC 62196 Type 2 Combo'), ('IEC_62196_T3A', 'IEC 62196 Type 3A'), ('IEC_62196_T3C', 'IEC 62196 Type 3C'), ('NEMA_5_20', 'NEMA 5-20'), ('NEMA_6_30', 'NEMA 6-30'), ('NEMA_6_50', 'NEMA 6-50'), ('NEMA_10_30', 'NEMA 10-30'), ('NEMA_10_50', 'NEMA 10-50'), ('NEMA_14_30', 'NEMA 14-30'), ('NEMA_14_50', 'NEMA 14-50'), ('PANTOGRAPH_BOTTOM_UP', 'Pantograph bottom up'), ('PANTOGRAPH_TOP_DOWN', 'Pantograph top down'), ('TESLA_R', 'Tesla Roadster'), ('TESLA_S', 'Tesla Supercharger'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='evse',
            name='evse_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evse',
            name='ingested_at',
            field=models.DateTimeField(help_text='Timestamp of the ingestion run that last processed this record.'),
        ),
        migrations.AlterField(
            model_name='evse',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evse',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('CHARGING', 'Charging'), ('INOPERATIVE', 'Inoperative'), ('OUTOFORDER', 'Out of order'), ('PLANNED', 'Planned'), ('REMOVED', 'Removed'), ('RESERVED', 'Reserved'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Canonical EVSE status. Unknown preserves unmappable upstream values safely.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ingested_at',
            field=models.DateTimeField(help_text='Timestamp of the ingestion run that last processed this record.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chargerlocation',
            index=models.Index(fields=['postal_code'], name='charger_loc_postal__3ea34c_idx'),
        ),
        migrations.RemoveField(
            model_name='chargerlocation',
            name='postcode',
        ),
    ]
